name: Test Build Utils

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_build_utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Set up Dana Server
        run: |
          git clone https://github.com/IlyasMoutawwakil/dana-server.git
          cd dana-server
          npm install
          npm start &

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/huggingface/optimum-benchmark.git
          pip install pytest
          pip install -e .

      - name: Run a benchmark
        run: optimum-benchmark --config-dir tests --config-name config --multirun

      - name: Run tests
        run: |
          pytest tests/test_build_utils.py
